---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 6/04/22 21:58
---

local ViewParser = require("view.ViewParser")



---@module View
---@param path string Path to view file
---@param data any Data to pass to view
function View(path, data)
    local self = {}

    --- File of view
    ---@type string
    self.content = getContent(path) or error("View not found: " .. path)

    --- Parse template to HTML string
    self.content = ViewParser:parse(self.content, data)

    return setmetatable(self, {
        __tostring = function()
            return self.content
        end
    })
end


--Function that returns the content of file as a string (or nil if the file doesn't exist)
function getContent(path)
    local file = require("io").open(path, "r")
    if file == nil then
        return nil
    end
    local content = file:read("*all")
    file:close()
    return content
end







return View