---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 2/04/22 14:38
---

---@module Table
local Table = {}



---Provide to create a read-only value/table.
---@param value any
---@see Thanks to https://stackoverflow.com/questions/28312409/how-can-i-implement-a-read-only-table-in-lua
function Table:readOnly(t)
    local proxies = setmetatable( {}, { __mode = "k" } )

    if type( t ) == "table" then
        -- check whether we already have a readonly proxy for this table
        local p = proxies[ t ]
        if not p then
            -- create new proxy table for t
            p = setmetatable( {}, {
                __index = function( _, k )
                    -- apply `readonly` recursively to field `t[k]`
                    return readOnly( t[ k ] )
                end,
                __newindex = function()
                    error( "table is readonly", 2 )
                end,
            } )
            proxies[ t ] = p
        end
        return p
    else
        -- non-tables are returned as is because primitives are immutable
        return t
    end
end




return Table