---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 2/04/22 14:38
---

---@module Table
local Table = {}

-- Create method that transform table as Read Only Table
function Table.readOnly(t)
    local proxy = {}
    setmetatable(proxy, {
        __index = t,
        __newindex = function()
            print("[ERROR : utils.Table] attempt to update a read-only table")
            error("[ERROR : utils.Table] attempt to update a read-only table")
        end
    })
    return proxy
end



return Table