---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 16:59
---

local json = require("json")
local Status = require("Status")


---@class JsonResponse : Response
---@param data any Value to transform as string
local function JsonResponse(data)
    local self = require("request.Response")()
    local jsonData = json.encode(data)

    ---Called to respond to client.
    ---@param request Request The client request to respond to.
    self.execute = function(request)
        request.setResponseHeaders({
            [':status'] = Status.OK,
            ["Content-Type"] = "application/json", -- Set the content type to json
            ["Content-Length"] = #jsonData -- Set the content length to the length of the json data
        })

        request.write(jsonData) -- Write the json data to the client
    end

    return self
end


return JsonResponse