---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 16:59
---

local Status = require("Status")
local View = require("view.View")


---@class ViewResponse : Response
---@param data any Value to transform as string
local function ViewResponse(path, data)
    local self = require("request.Response")()
    data = data or {}

    ---Called to respond to client.
    ---@param request Request The client request to respond to.
    self.execute = function(request)
        local view = tostring(View(path, data))

        request.setResponseHeaders({
            [':status'] = Status.OK,
            ['content-type'] = 'text/html',
            ["Content-Length"] = #view -- Set the content length to the length of the json data
        })

        request.write(view) -- Write the json data to the client
    end

    return self
end


return ViewResponse