---
--- @module HttpServer
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 11:28
---

local httpServerM = require "http.server"
local headersM = require 'http.headers'
local Status = require 'Status'
local Request = require 'Request'


---@field public server http.server
---@field public route RouteRepository
---@field public timeout number @default 10
local self = {
    server = nil, -- Server
    routeRepository = require "RouteRepository", -- Route
    timeout = 10, -- Client timeout in seconds
}

-- Creating the http(s) server
-- @param string host Host of server (default: 0.0.0.0)
-- @param port Port of server (default: 0)
self.init = function(host, port)
    host = host or "0.0.0.0"
    port = port or 0

    self.server = httpServerM.listen{
        host = host,
        port = port,
        onstream = self.onRequest,
        version = 1.1,
    }

    -- self.server.settimeout(self.timeout)
    print(("Create HttpServer on port %d"):format(port))
end

---Listening for http requests
self.listen = function()
    self.server:listen()
    self.server:loop()
end

-- Used to stop server
self.stop = function()
    print("HttpServer stop")
    self.server:close()
end


self.onRequest = function(sv, stream)
    print("Connection client")
    local request = Request.new(stream) -- Create request
    local path = request.getRequestHeader('path') or '/' -- Get path

    local found, response = self.routeRepository.tryRoute(path, request) -- Try to find a route
    if not found then
        request.setResponseHeaders({
            [':status'] = Status.NOT_FOUND
        })
    else
        if response ~= nil then
            response.execute(request) -- Execute the response builder
        end
        request.setResponseHeaders({
            [':status'] = Status.OK -- TODO CHange by NO_CONTENT but remove write and ... from Request
        })
    end
end


---Adding route to http server request dispatcher
---@param path string Route path
---@param handler function handler called when request
self.route = function(path, handler)
    self.routeRepository.add(path, handler)
end


return {
    init = self.init,
    listen = self.listen,
    stop = self.stop,
    route = self.route
}
