---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 11:33
---

local httpServer = require("HttpServer")
local Status = require 'Status'
local ViewResponse = require 'request.ViewResponse'
local JsonResponse = require 'request.JsonResponse'

-- Init http server
httpServer.init("localhost", 8080)



httpServer.route("/", {"GET", "POST"}, function(request)
    if not request.cookie["value"] then
        request.cookie["value"] = "Rien du tout"
    end

    if request.post["value"] then
        print("POST: " .. request.post["value"])
        request.cookie["value"] = request.post["value"]
    end

    return ViewResponse("index.html", {
        value = request.cookie["value"],
    })
end)

-- Start http server
httpServer.listen()

-- Stop http server
httpServer.stop()


