---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 11:33
---

local httpServer = require("HttpServer")
local Status = require 'Status'


-- Init http server
httpServer.init("localhost", 8080)

httpServer.route("/", function(request)
    request.setResponseHeaders({
        status = Status.OK,
    })

    request.write("Hello Benjamin!\n")
    request.write("Haha!\n")
end)

-- Start http server
httpServer.listen()

-- Stop http server
httpServer.stop()


