---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 11:33
---

local httpServer = require("HttpServer")
local Status = require 'Status'
local ViewResponse = require 'request.ViewResponse'

-- Init http server
httpServer.init("localhost", 8080)

httpServer.route("/", "GET", function(request)

    return ViewResponse("index.html", {
        name = "Benja"
    })
end)

-- Start http server
httpServer.listen()

-- Stop http server
httpServer.stop()


