---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 12:08
---

---@module RouteRepository
---@field public routes {path:string, handler:fun(request:Request):Response|nil}[] Routes of server
local self = {
    routes = {}, -- Routes table
}


---Adding route to http server request dispatcher
---@param path string Route path
---@param handler fun(request:Request):Response|nil handler called when request
self.add = function(path, handler)
    local route = {
        path = path,
        handler = handler
    }
    table.insert(self.routes, route)
end


---Adding route to http server request dispatcher
---@param url string Url
---@param request Request Request object
---@return (boolean, Response) If route is found, return true and response, otherwise return false and nil
self.tryRoute = function(url, request)
    -- Extract path from request
    local path = url:match("^(/[^?]*)") or '/'
    -- Replace all //* by /
    path = path:gsub("//+", "/")
    print(path)

    for _, route in pairs(self.routes) do
        if route.path == url then
            return true, route.handler(request) -- Route found
        end
    end
    return false, nil -- Route not found
end


return self