---
--- @module RouteRepository
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benjamin.
--- DateTime: 1/04/22 12:08
---


local self = {
    routes = {}, -- Routes table
}


---Adding route to http server request dispatcher
---@param path string Route path
---@param handler function handler called when request
self.add = function(path, handler)
    local route = {
        path = path,
        handler = handler
    }
    table.insert(self.routes, route)
end


---Adding route to http server request dispatcher
---@param url string Url
---@param request Request Request object
self.tryRoute = function(url, request)
    -- local path = url:match("^[^/]*") -- Path so without params
    for _, route in pairs(self.routes) do
        if route.path == url then
            route.handler(request)
            return true -- Route found
        end
    end
    return false -- Route not found
end


return {
    add = self.add,
    tryRoute = self.tryRoute
}